title:            FuriKuri's Blog
url:              http://furikuri.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
timezone:         Europe/Berlin
paginate: 5
gems:
  - jemoji
